<?php
// $Id$
/**
 * @file fail.module
 * Designed to create failures we can debug.
 */


function fail_init() {

  $query = new EntityFieldQuery();
  $entities = $query->entityCondition('entity_type', 'node')
  ->propertyCondition('type', 'your_node_type')
  ->propertyCondition('title', 'your node title')
  ->propertyCondition('status', 1)
  ->range(0,1)
  ->execute();

  //if (!empty($entities['node'])) {
    //$node = node_load($entities);
    $node = node_load1(array_shift(array_keys($entities['node'])));
  //}
}
